mysite/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import reverse

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'
urlpatterns = [
    url(r'^search$', views.search, name='search'),
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^search/(?P<keyword>.*)$', views.IndexView.as_view(), name='indexsearch'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import datetime

from django.db import models
from django.utils import timezone

# Create your models here.


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    # ...
    def was_published_recently(self):
        now = timezone.now()
        return now >= self.pub_date >= now - datetime.timedelta(days=1)

    # ...
    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    # ...
    def __str__(self):
        return self.choice_text

mysite/views.py
from django.shortcuts import render


def index(request):
    return render(request, 'mysite/index.html', {})

polls/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Choice, Question

# import the logging library
import logging

# Get an instance of a logger
logger = logging.getLogger(__name__)


class IndexView(generic.ListView):

    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'
    keyword = None

    def __init__(self, **kwargs):
        super(IndexView, self).__init__()
        """
        Constructor. Called in the URLconf; can contain helpful extra
        keyword arguments, and other things.
        """

    def dispatch(self, request, *args, **kwargs):
        """ had to override this to save the keyword value for some reason??? """
        # Go through keyword arguments, and either save their values to our
        # instance, or raise an error.
        logger.debug(len(kwargs))
        for key in kwargs:
            logger.debug("kwargs key=%s value=%s" % (key, None))

        if 'keyword' in kwargs:
            logger.debug("keyword=%s" % (kwargs['keyword']))
            self.keyword = kwargs['keyword']

        # Go through keyword arguments, and either save their values to our
        # instance, or raise an error.
        logger.debug(len(args))
        for key, value in args:
            logger.debug("args key=%s value=%s" % (key, value))

        return super(IndexView, self).dispatch(request, args, kwargs)

    def get_queryset(self):
        logger.debug("index keyword=%s" % self.keyword)

        if self.keyword is None:
            """Return the last five published questions."""
            return Question.objects.filter(
                pub_date__lte=timezone.now()
            ).order_by('-pub_date')[:5]
        else:
            """Return last five matching questions."""
            return Question.objects.filter(
                pub_date__lte=timezone.now(),
                question_text__contains=self.keyword
            ).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """ Excludes any questions that aren't published yet.  """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def search(request):
    first_word = request.POST['question_text']
    if len(first_word) == 0:
        first_word = None
    return HttpResponseRedirect(reverse('polls:indexsearch', args=(first_word,)))


def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': question,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

mysite/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Python Polls</title>
    <link rel="stylesheet" href="/static/style.css" />
</head>
<body>
<div>
    <a href="/">Home</a>
</div>
{% block content %}{% endblock %}
</body>
</html>

mysite/templates/mysite/index.html
{% extends "base.html" %}

{% block content %}
<h1>Python Polling</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:search' %}" method="post">
{% csrf_token %}
<label for="question_text">Search Polls</label><br />
<input type="text" name="question_text" id="question_text" placeholder="Enter a keyword"
      pattern="\w*" required="required" title="Enter a keyword without spaces"/>
<input type="submit" value="Search" />
</form>

<div>
  <a href="{% url 'polls:index' %}">Current Polls</a>
  <a href="{% url 'admin:index' %}">Admin Site</a>
</div>
{% endblock %}

polls/templates/polls/detail.html
{% extends "base.html" %}

{% block content %}
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
{% endblock %}

polls/templates/polls/index.html
{% extends "base.html" %}

{% block content %}
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}
{% endblock %}

polls/templates/polls/results.html
{% extends "base.html" %}

{% block content %}
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>
{% endblock %}